$(document).ready(function(){
    $("#circle1").click(function(){
	$("#circle1").animate({
	    left:'400px',
		down:'400px',
	    opacity:'0.5',
	    height:'500px',
	    width:'500px'  
	})
    });
});
